# Generated by Django 3.0.4 on 2020-12-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_auto_20201222_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
