# Generated by Django 3.0.4 on 2021-01-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_orderitem_refund_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='online_payment',
        ),
    ]
