# Generated by Django 3.0.4 on 2021-01-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0007_auto_20210114_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
