# Generated by Django 3.0.4 on 2021-01-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0008_auto_20210115_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundrequest',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_requested',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='RefundRequest',
        ),
    ]
