# Generated by Django 3.0.4 on 2021-01-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0010_remove_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='initial_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
