# Generated by Django 3.0.4 on 2021-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0011_auto_20210116_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rp_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rp_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
