# Generated by Django 3.0.4 on 2021-01-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0012_auto_20210118_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rp_payment_id',
        ),
    ]
