# Generated by Django 3.0.4 on 2020-12-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Products/ProductImages')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
            ],
        ),
    ]
