# Generated by Django 3.0.4 on 2020-12-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
