# Generated by Django 3.0.4 on 2020-11-02 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_category_num_of_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_set',
        ),
        migrations.CreateModel(
            name='ProductAndProductSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
                ('product_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.ProductSet')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAndCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(through='Products.ProductAndCollection', to='Products.Product'),
        ),
        migrations.AddField(
            model_name='productset',
            name='products',
            field=models.ManyToManyField(through='Products.ProductAndProductSet', to='Products.Product'),
        ),
    ]
